import React, { createContext, useState, useContext, useEffect, useCallback } from 'react';

type Language = 'vi' | 'en';

const translations = {
  vi: {
    // General
    search: 'Tìm kiếm...',
    close: 'Đóng',
    cancel: 'Huỷ',
    save: 'Lưu',
    send: 'Gửi',
    today: 'Hôm nay',
    title: 'Tiêu đề',
    // Top Sidebar
    mode: 'Chế độ',
    light: 'Sáng',
    dark: 'Tối',
    system: 'Hệ thống',
    accent: 'Màu nhấn',
    language: 'Ngôn ngữ',
    logout: 'Đăng xuất',
    newNotifications: 'Bạn có thông báo mới',
    account: 'Tài khoản',
    settings: 'Cài đặt',
    accountSettings: 'Cài đặt Tài khoản & Hệ thống',
    accountSlogan: 'Tinh chỉnh mọi thứ theo cách của bạn.',
    appearance: 'Giao diện',
    // Left Sidebar
    dashboard: 'Trang chủ',
    newsfeed: 'Bảng tin',
    drive: 'Lưu trữ',
    tasklist: 'Công việc',
    contacts: 'Danh bạ',
    calendar: 'Lịch hẹn',
    notes: 'Ghi chú',
    blog: 'Bài viết',
    email: 'Email',
    meeting: 'Cuộc họp',
    chat: 'Trao đổi',
    training: 'Đào tạo',
    // Right Sidebar
    activityFeed: 'Luồng hoạt động',
    systemUpdate: 'Cập nhật hệ thống',
    systemUpdateDesc: 'Phiên bản 2.5.1 đã sẵn sàng.',
    newUser: 'Người dùng mới',
    newUserDesc: 'Alex đã tham gia nhóm của bạn.',
    reportGenerated: 'Báo cáo đã tạo',
    reportGeneratedDesc: 'Báo cáo doanh thu tháng đã sẵn sàng.',
    settingsChanged: 'Thay đổi cài đặt',
    settingsChangedDesc: 'Tuỳ chọn thông báo đã được cập nhật.',
    activity_action_login: 'đã đăng nhập vào hệ thống.',
    activity_action_file_edit: 'đã chỉnh sửa tài liệu',
    activity_action_task_complete: 'đã hoàn thành công việc',
    activity_action_meeting_scheduled: 'đã lên lịch cuộc họp',
    activity_action_comment_added: 'đã bình luận về',
    // Auth
    welcomeBack: 'Chào mừng trở lại!',
    createYourAccount: 'Tạo tài khoản của bạn',
    signInToContinue: 'Đăng nhập để tiếp tục vào dashboard.',
    getStarted: 'Bắt đầu với dashboard tuyệt vời của chúng tôi.',
    signInWithGoogle: 'Đăng nhập với Google',
    or: 'HOẶC',
    emailAddress: 'Địa chỉ email',
    password: 'Mật khẩu',
    confirmPassword: 'Xác nhận mật khẩu',
    login: 'Đăng nhập',
    createAccount: 'Tạo tài khoản',
    dontHaveAccount: 'Chưa có tài khoản?',
    alreadyHaveAccount: 'Đã có tài khoản?',
    signUp: 'Đăng ký',
    verificationSent: 'Email xác thực đã được gửi. Vui lòng kiểm tra hộp thư của bạn.',
    pleaseVerifyEmail: 'Vui lòng xác thực email của bạn để tiếp tục.',
    // Main Content
    yourProjects: 'Dự án của bạn',
    // Banner
    welcomeUser: 'Chào mừng trở lại, {{userName}}!',
    welcomeDesc: 'Dashboard của bạn đã sẵn sàng. Bạn có thể xem phân tích bán hàng gần đây, quản lý người dùng và kiểm tra trạng thái hệ thống. Hãy làm cho hôm nay thật năng suất!',
    viewAnalytics: 'Xem phân tích',
    // Email Client
    inbox: 'Hộp thư đến',
    unreadMessages: '{{count}} tin nhắn chưa đọc',
    compose: 'Soạn thư',
    linkToProject: 'Gắn vào Dự án',
    selectEmailToRead: 'Chọn một email để đọc',
    syncWithGmail: 'Đồng bộ với Gmail',
    primary: 'Chính',
    promotions: 'Quảng cáo',
    social: 'Xã hội',
    starred: 'Gắn dấu sao',
    // Calendar
    createEvent: 'Tạo sự kiện',
    month: 'Tháng',
    week: 'Tuần',
    day: 'Ngày',
    syncWithGoogle: 'Đồng bộ với Lịch Google',
    syncing: 'Đang đồng bộ...',
    syncSuccess: 'Đồng bộ thành công!',
    eventsOn: 'Sự kiện ngày',
    noEventsScheduled: 'Không có sự kiện nào được lên lịch.',
    // Notes
    syncWithKeep: 'Đồng bộ với Keep',
    takeANote: 'Tạo một ghi chú...',
    pinNote: 'Ghim ghi chú',
    unpinNote: 'Bỏ ghim',
    // Blog
    latestPosts: 'Bài viết mới nhất',
    newPost: 'Viết bài mới',
    publish: 'Xuất bản',
    saveDraft: 'Lưu nháp',
    postTitle: 'Tiêu đề bài viết',
    writeYourStory: 'Hãy viết câu chuyện của bạn...',
    backToBlog: 'Quay lại Blog',
    postSettings: 'Cài đặt bài viết',
    tags: 'Thẻ (phân cách bằng dấu phẩy)',
    featuredImageUrl: 'URL Ảnh đại diện',
    blogSettings: 'Cài đặt Blog',
    blogSettingsDesc: 'Quản lý kết nối Blogger và đồng bộ bài viết.',
    zimbraSettings: 'Cài đặt Zimbra',
    zimbraSettingsDesc: 'Quản lý kết nối và đồng bộ email từ máy chủ Zimbra.',
    zimbraEmail: 'Email Zimbra',
    zimbraPassword: 'Mật khẩu Zimbra',
    zimbraServer: 'Máy chủ Zimbra (URL)',
    bloggerUrl: 'URL trang Blogger.com',
    fetchFrequency: 'Tần suất',
    daily: 'Hàng ngày',
    weekly: 'Hàng tuần',
    manual: 'Thủ công',
    doesNotRepeat: 'Không lặp lại',
    monthly: 'Hàng tháng',
    yearly: 'Hàng năm',
    fetchNow: 'Lấy bài viết ngay',
    saveSettings: 'Lưu Cài đặt',
    fetchingPosts: 'Đang lấy bài viết...',
    fetchSuccess: 'Đã lấy thành công {{count}} bài viết mới!',
    fetchError: 'Lỗi khi lấy bài viết. Vui lòng thử lại.',
    driveSettings: 'Cài đặt Drive',
    driveSettingsDesc: 'Quản lý kết nối Drive và thiết lập đồng bộ.',
    driveFolderUrl: 'URL thư mục Drive',
    fetchFiles: 'Đồng bộ File',
    fetchingFiles: 'Đang đồng bộ...',
    fetchDriveError: 'Lỗi khi đồng bộ File. Vui lòng thử lại.',
    publishSuccess: 'Bài viết đã được xuất bản thành công!',
    publishSuccessBlogger: 'Đã đồng bộ lên Blogger.',
    showLess: 'Ẩn bớt',
    allTags: 'Tất cả thẻ',
    clearFilter: 'Xóa bộ lọc',
    searchPlaceholderBlog: 'Tìm kiếm bài viết...',
    allStatuses: 'Tất cả trạng thái',
    statusPublished: 'Đã xuất bản',
    statusDraft: 'Bản nháp',
    statusArchived: 'Đã lưu trữ',
    noArticlesFound: 'Không tìm thấy bài viết nào',
    noArticlesFoundDesc: 'Thử thay đổi từ khóa tìm kiếm hoặc bộ lọc thẻ để tìm thấy nội dung mong muốn.',
    clearAllFilters: 'Xóa tất cả bộ lọc',
    blogAssistant: 'Trợ lý Blog',
    blogAssistantSlogan: 'Hỏi đáp, tóm tắt, và lấy ý tưởng từ các bài viết của bạn.',
    askAboutArticles: 'Hỏi bất cứ điều gì về các bài viết...',
    scheduleDiscussion: 'Lên lịch thảo luận',
    discussArticle: 'Thảo luận bài viết: {{title}}',
    previousPage: 'Trang trước',
    nextPage: 'Trang sau',
    // Contacts
    createContact: 'Tạo liên hệ mới',
    personalContact: 'Liên hệ cá nhân',
    allContacts: 'Tất cả liên hệ',
    fullName: 'Họ và tên',
    jobTitle: 'Chức vụ',
    phoneNumber: 'Số điện thoại',
    avatarUrl: 'URL Ảnh đại diện',
    companyDepartment: 'Công ty / Phòng ban',
    avatarUrlOptional: 'URL ảnh đại diện (tùy chọn)',
    saveContact: 'Lưu liên hệ',
    searchContactsPlaceholder: 'Tìm theo tên, email, phòng ban...',
    importContacts: 'Nhập danh bạ',
    exportContacts: 'Xuất danh bạ',
    syncWithGoogleContacts: 'Đồng bộ với Google Contacts',
    // Tasklist
    syncWithGoogleTasks: 'Đồng bộ với Google Tasks',
    // Training Module
    trainingDashboard: 'Dashboard Đào tạo',
    trainingSlogan: 'Lớp học số – Học mọi lúc, kết nối mọi nơi',
    myClasses: 'Các lớp học của tôi',
    createClass: 'Tạo lớp học',
    stream: 'Bảng tin',
    classwork: 'Bài tập trên lớp',
    people: 'Mọi người',
    grades: 'Điểm số',
    allTopics: 'Tất cả chủ đề',
    syncWithGoogleClassroom: 'Đồng bộ Classroom',
    // Google Sync
    connectGoogleAccount: 'Kết nối tài khoản Google',
    disconnect: 'Ngắt kết nối',
    connectedAs: 'Đã kết nối với tài khoản',
    syncStatus: 'Trạng thái đồng bộ',
    service: 'Dịch vụ',
    status: 'Trạng thái',
    sync: 'Đồng bộ',
    connected: 'Đã kết nối',
    notConnected: 'Chưa kết nối',
    connect: 'Kết nối',
    // Settings Page
    profile: 'Hồ sơ',
    connectionsAndSync: 'Kết nối & Đồng bộ',
    effectsAndSound: 'Hiệu ứng & Âm thanh',
    aiVoiceSettings: 'Cài đặt Giọng nói AI',
    manageYourProfile: 'Quản lý thông tin cá nhân của bạn.',
    customizeAppearance: 'Tùy chỉnh giao diện và màu sắc của ứng dụng.',
    chooseLanguage: 'Chọn ngôn ngữ hiển thị cho ứng dụng.',
    manageEffects: 'Quản lý các hiệu ứng hình ảnh và âm thanh.',
    configureAiAssistant: 'Cấu hình giọng nói và hành vi của Trợ lý AI.',
    manageIntegrations: 'Quản lý kết nối và đồng bộ với các dịch vụ bên ngoài.',
    userManagement: 'Phân quyền người dùng',
    userManagementDesc: 'Quản lý vai trò và quyền truy cập của người dùng.',
    userManagementTitle: 'Quản lý Phân quyền',
    userManagementSlogan: 'Xây dựng cấu trúc, bảo vệ dữ liệu, trao quyền hiệu quả.',
    user: 'Người dùng',
    role: 'Vai trò',
    active: 'Hoạt động',
    role_superadmin: 'Super Admin',
    role_superadmin_desc: 'Toàn quyền truy cập tất cả cài đặt và quản lý người dùng.',
    role_admin: 'Admin',
    role_admin_desc: 'Có thể tạo và quản lý nội dung, nhưng không thể thay đổi cài đặt hệ thống hoặc vai trò người dùng.',
    role_member: 'Member',
    role_member_desc: 'Quyền truy cập tiêu chuẩn để xem và tương tác với nội dung được chia sẻ.',
    updateRoleSuccess: 'Cập nhật vai trò thành công!',
    cannotChangeOwnRole: 'Không thể thay đổi vai trò của chính mình.',
    userList: 'Danh sách người dùng',
    createUser: 'Tạo người dùng',
    addUser: 'Thêm người dùng',
    orgChart: 'Sơ đồ tổ chức',
    orgChartConfig: 'Tổ chức',
    department: 'Phòng ban',
    position: 'Chức vụ',
    requestsAndApprovals: 'Phê duyệt',
    requests: 'Yêu cầu',
    approvals: 'Phê duyệt',
    newRequest: 'Tạo yêu cầu mới',
    requestTitle: 'Tiêu đề',
    requestType: 'Loại yêu cầu',
    requestContent: 'Nội dung',
    statusPending: 'Đang chờ',
    statusApproved: 'Đã duyệt',
    statusRejected: 'Đã từ chối',
    approve: 'Phê duyệt',
    reject: 'Từ chối',
    leaveRequest: 'Xin nghỉ phép',
    equipmentRequest: 'Yêu cầu thiết bị',
    otherRequest: 'Khác',
    approver: 'Người phê duyệt',
    selectApprover: 'Chọn người phê duyệt',
    recentlyViewed: 'Xem gần đây',
    websiteData: 'Quản trị',
    projects: 'Dự án',
    websiteDataManagement: 'Quản trị hệ thống',
    homePage: 'Trang chủ',
    pages: 'Trang tĩnh',
    media: 'Thư viện',
    websiteSettings: 'Cài đặt',
    // AI Widget & Settings
    visualEffects: 'Hiệu ứng hình ảnh',
    cursorTrails: 'Hiệu ứng con trỏ',
    cursorTrailsDesc: 'Bật hiệu ứng con trỏ chuột để theo dõi mượt mà hơn.',
    soundEffects: 'Hiệu ứng âm thanh',
    enableSoundEffects: 'Bật hiệu ứng âm thanh',
    enableSoundEffectsDesc: 'Bật âm thanh khi nhấp chuột và tương tác.',
    aiVoice: 'Giọng nói AI',
    enableAiVoice: 'Kích hoạt giọng nói',
    enableAiVoiceDesc: 'Bật/tắt tính năng đọc văn bản của Trợ lý AI.',
    robotEffect: 'Hiệu ứng Robot',
    robotEffectDesc: 'Áp dụng hiệu ứng giọng robot cho Trợ lý AI.',
    voiceModel: 'Giọng đọc',
    voiceModelDesc: 'Chọn giọng đọc cho Trợ lý AI.',
    selectVoice: 'Chọn giọng đọc',
    loadingVoices: 'Đang tải giọng đọc...',
    // Drive & Meeting Sync
    syncWithDrive: 'Đồng bộ với Drive',
    syncWithMeetingsCalendar: 'Đồng bộ với Lịch',
    syncWithCalendar: 'Đồng bộ với Lịch',
    addToCalendar: 'Thêm vào Lịch Google',
    syncWithGoogleChat: 'Đồng bộ với Lịch',
    // Newsfeed
    whatAreYouThinking: 'Bạn đang nghĩ gì, {{userName}}?',
    post: 'Đăng bài',
    photoVideo: 'Ảnh/Video',
    tagFriends: 'Gắn thẻ bạn bè',
    feelingActivity: 'Cảm xúc/Hoạt động',
    checkIn: 'Chấm công',
    audience: 'Đối tượng',
    audienceCompany: 'Toàn công ty',
    audienceGroup: 'Nhóm của bạn',
    audiencePrivate: 'Chỉ mình tôi',
    isFeeling: 'đang cảm thấy',
    with: 'cùng với',
    at: 'tại',
    // Check-in Module
    timekeeping: 'Chấm công',
    timekeepingHistory: "Hôm nay",
    checkInSuccess: 'Chấm công vào thành công!',
    checkOutSuccess: 'Chấm công ra thành công!',
    currentStatus: 'Trạng thái hiện tại',
    notCheckedIn: 'Chưa chấm công',
    checkedInAt: 'Đã vào lúc',
    workingDuration: 'Thời gian làm việc',
    location: 'Vị trí',
    date: 'Ngày',
    duration: 'Thời lượng',
    checkInTime: 'Giờ vào',
    checkOutTime: 'Giờ ra',
    checkInButton: 'Chấm Công Vào',
    checkOutButton: 'Chấm Công Ra',
    checkInBiometric: 'Vào ca bằng vân tay',
    checkOutBiometric: 'Ra ca bằng vân tay',
    registerBiometric: 'Đăng ký vân tay',
    biometricRegistered: 'Đăng ký vân tay thành công!',
    biometricError: 'Lỗi xác thực vân tay.',
    registerBiometricPrompt: 'Bạn chưa đăng ký vân tay. Bạn có muốn đăng ký ngay bây giờ không?',
    editProfile: 'Chỉnh sửa hồ sơ',
    saveProfile: 'Lưu hồ sơ',
    profileUpdated: 'Cập nhật hồ sơ thành công!',
    profileUpdateError: 'Có lỗi xảy ra khi cập nhật hồ sơ.',
    saveSuccess: 'Cài đặt đã được lưu thành công!',
    changeAvatar: 'Thay đổi ảnh',
    comments: 'Bình luận',
    addComment: 'Thêm bình luận',
    noComments: 'Chưa có bình luận nào.',
    writeComment: 'Viết bình luận...',
    weeklyWorkHours: 'Giờ làm việc tuần này',
    hours: 'giờ',
    dayMon: 'T2',
    dayTue: 'T3',
    dayWed: 'T4',
    dayThu: 'T5',
    dayFri: 'T6',
    daySat: 'T7',
    daySun: 'CN',
    activeSession: 'Phiên làm việc',
    authenticating: 'Đang xác thực...',
    biometricsNotSupported: 'Sinh trắc học không được hỗ trợ trên thiết bị này.',
    checkedIn: 'Đã chấm công',
    checkedOut: 'Đã tan ca',
    // Dashboard Customization
    customizeDashboard: 'Tùy chỉnh',
    dashboardWidgets: 'Tiện ích Dashboard',
    dashboardWidgetsDesc: 'Chọn các tiện ích bạn muốn hiển thị trên trang tổng quan.',
    upcomingEvents: 'Sự kiện sắp tới',
    quickTasks: 'Việc cần làm nhanh',
    recentNotes: 'Ghi chú gần đây',
    recentlyViewedItems: 'Xem gần đây',
    noUpcomingEvents: 'Không có sự kiện nào sắp tới.',
    noPendingTasks: 'Không có công việc nào cần làm.',
    noRecentNotes: 'Không có ghi chú nào.',
    viewAll: 'Xem tất cả',
    widget_events_desc: 'Hiển thị các sự kiện và cuộc họp sắp tới.',
    widget_tasks_desc: 'Hiển thị các công việc chưa hoàn thành.',
    widget_notes_desc: 'Hiển thị các ghi chú được tạo gần đây.',
    widget_recent_desc: 'Hiển thị các mục bạn đã truy cập gần đây.',
    widget_newsfeed_desc: 'Xem trước bài đăng mới nhất trên bảng tin nội bộ.',
    widget_checkin_desc: 'Xem trạng thái chấm công hiện tại của bạn.',
    widget_drive_desc: 'Xem các tệp được sửa đổi gần đây trong Lưu trữ.',
    widget_tasks_link_desc: 'Xem tóm tắt các công việc chưa hoàn thành.',
    widget_contacts_desc: 'Xem nhanh một vài liên hệ trong danh bạ.',
    widget_calendar_link_desc: 'Xem các sự kiện và cuộc họp sắp tới.',
    widget_notes_link_desc: 'Xem trước các ghi chú gần đây nhất của bạn.',
    widget_blog_desc: 'Xem bài viết hoặc blog mới nhất.',
    widget_training_desc: 'Xem lớp học hoặc khóa đào tạo sắp tới.',
    widget_email_desc: 'Xem trước các email chưa đọc quan trọng.',
    widget_meeting_desc: 'Xem cuộc họp trực tuyến sắp diễn ra.',
    widget_chat_desc: 'Xem các kênh trao đổi có tin nhắn mới.',
    // Global Search
    searchAllPlaceholder: 'Tìm kiếm bài viết, tài liệu, liên hệ...',
    noResultsFound: 'Không tìm thấy kết quả nào.',
    resultsBlog: 'Bài viết',
    resultsFiles: 'Tài liệu',
    resultsContacts: 'Liên hệ',
    resultsTasks: 'Công việc',
    resultsEvents: 'Sự kiện',
    resultsMessages: 'Tin nhắn',
    openNavigationMenu: 'Mở danh mục điều hướng',
    submitSearch: 'Thực hiện tìm kiếm',
    // Projects
    projectList: 'Danh sách dự án',
    newProject: 'Tạo dự án mới',
    projectName: 'Tên dự án',
    projectDesc: 'Mô tả dự án',
    projectStatus: 'Trạng thái',
    projectDueDate: 'Hạn chót',
    projectDepartment: 'Phòng ban',
    exportCSV: 'Xuất CSV',
    exportPDF: 'Xuất PDF',
    searchProjects: 'Tìm kiếm dự án theo tên hoặc mô tả...',
    allDepartments: 'Tất cả phòng ban',
    overdue: 'Quá hạn',
    thisWeek: 'Tuần này',
    thisMonth: 'Tháng này',
    progress: 'Tiến độ',
  },
  en: {
    // General
    search: 'Search...',
    close: 'Close',
    cancel: 'Cancel',
    save: 'Save',
    send: 'Send',
    today: 'Today',
    title: 'Title',
    // Top Sidebar
    mode: 'Mode',
    light: 'Light',
    dark: 'Dark',
    system: 'System',
    accent: 'Accent',
    language: 'Language',
    logout: 'Logout',
    newNotifications: 'You have new notifications',
    account: 'Account',
    settings: 'Settings',
    accountSettings: 'Account & System Settings',
    accountSlogan: 'Fine-tune everything to your liking.',
    appearance: 'Appearance',
    // Left Sidebar
    dashboard: 'Dashboard',
    newsfeed: 'Newsfeed',
    drive: 'Storage',
    tasklist: 'Tasks',
    contacts: 'Contacts',
    calendar: 'Appointments',
    notes: 'Notes',
    blog: 'Blog',
    email: 'Email',
    meeting: 'Meeting',
    chat: 'Exchange',
    training: 'Training',
    // Right Sidebar
    activityFeed: 'Activity Feed',
    systemUpdate: 'System Update',
    systemUpdateDesc: 'Version 2.5.1 is now available.',
    newUser: 'New User',
    newUserDesc: 'Alex joined your team.',
    reportGenerated: 'Report Generated',
    reportGeneratedDesc: 'Monthly sales report is ready.',
    settingsChanged: 'Settings Changed',
    settingsChangedDesc: 'Notifications preferences updated.',
    activity_action_login: 'has logged into the system.',
    activity_action_file_edit: 'edited the document',
    activity_action_task_complete: 'completed the task',
    activity_action_meeting_scheduled: 'scheduled the meeting',
    activity_action_comment_added: 'commented on',
    // Auth
    welcomeBack: 'Welcome Back!',
    createYourAccount: 'Create Your Account',
    signInToContinue: 'Sign in to continue to your dashboard.',
    getStarted: 'Get started with our awesome dashboard.',
    signInWithGoogle: 'Sign in with Google',
    or: 'OR',
    emailAddress: 'Email address',
    password: 'Password',
    confirmPassword: 'Confirm Password',
    login: 'Login',
    createAccount: 'Create Account',
    dontHaveAccount: "Don't have an account?",
    alreadyHaveAccount: 'Already have an account?',
    signUp: 'Sign Up',
    verificationSent: 'Verification email sent. Please check your inbox.',
    pleaseVerifyEmail: 'Please verify your email to continue.',
    // Main Content
    yourProjects: 'Your Projects',
    // Banner
    welcomeUser: 'Welcome Back, {{userName}}!',
    welcomeDesc: 'Your dashboard is ready. You can view recent sales analytics, manage users, and check system status. Let\'s make today productive!',
    viewAnalytics: 'View Analytics',
    // Email Client
    inbox: 'Inbox',
    unreadMessages: '{{count}} unread messages',
    compose: 'Compose',
    linkToProject: 'Link to Project',
    selectEmailToRead: 'Select an email to read',
    syncWithGmail: 'Sync with Gmail',
    primary: 'Primary',
    promotions: 'Promotions',
    social: 'Social',
    starred: 'Starred',
    // Calendar
    createEvent: 'Create Event',
    month: 'Month',
    week: 'Week',
    day: 'Day',
    syncWithGoogle: 'Sync with Google Calendar',
    syncing: 'Syncing...',
    syncSuccess: 'Sync successful!',
    eventsOn: 'Events on',
    noEventsScheduled: 'No events scheduled.',
    // Notes
    syncWithKeep: 'Sync with Keep',
    takeANote: 'Take a note...',
    pinNote: 'Pin note',
    unpinNote: 'Unpin note',
    // Blog
    latestPosts: 'Latest Posts',
    newPost: 'New Post',
    publish: 'Publish',
    saveDraft: 'Save Draft',
    postTitle: 'Post Title',
    writeYourStory: 'Write your story...',
    backToBlog: 'Back to Blog',
    postSettings: 'Post Settings',
    tags: 'Tags (comma separated)',
    featuredImageUrl: 'Featured Image URL',
    blogSettings: 'Blog Settings',
    blogSettingsDesc: 'Manage Blogger connection and sync posts.',
    zimbraSettings: 'Zimbra Settings',
    zimbraSettingsDesc: 'Manage connection and sync email from Zimbra server.',
    zimbraEmail: 'Zimbra Email',
    zimbraPassword: 'Zimbra Password',
    zimbraServer: 'Zimbra Server (URL)',
    bloggerUrl: 'Blogger.com Page URL',
    fetchFrequency: 'Fetch Frequency',
    daily: 'Daily',
    weekly: 'Weekly',
    manual: 'Manual',
    doesNotRepeat: 'Does not repeat',
    monthly: 'Monthly',
    yearly: 'Yearly',
    fetchNow: 'Fetch Posts Now',
    saveSettings: 'Save Settings',
    fetchingPosts: 'Fetching posts...',
    fetchSuccess: 'Successfully fetched {{count}} new posts!',
    fetchError: 'Error fetching posts. Please try again.',
    driveSettings: 'Drive Settings',
    driveSettingsDesc: 'Manage Drive connection and sync settings.',
    driveFolderUrl: 'Drive Folder URL',
    fetchFiles: 'Sync Files',
    fetchingFiles: 'Syncing files...',
    fetchDriveError: 'Error syncing files. Please try again.',
    publishSuccess: 'Post published successfully!',
    publishSuccessBlogger: 'Synced to Blogger.',
    showLess: 'Show Less',
    allTags: 'All Tags',
    clearFilter: 'Clear Filter',
    searchPlaceholderBlog: 'Search articles...',
    allStatuses: 'All statuses',
    statusPublished: 'Published',
    statusDraft: 'Draft',
    statusArchived: 'Archived',
    noArticlesFound: 'No articles found',
    noArticlesFoundDesc: 'Try changing your search terms or tag filters to find what you\'re looking for.',
    clearAllFilters: 'Clear all filters',
    blogAssistant: 'Blog Assistant',
    blogAssistantSlogan: 'Ask, summarize, and get ideas from your articles.',
    askAboutArticles: 'Ask anything about the articles...',
    scheduleDiscussion: 'Schedule Discussion',
    discussArticle: 'Discuss article: {{title}}',
    previousPage: 'Previous Page',
    nextPage: 'Next Page',
    // Contacts
    createContact: 'Create New Contact',
    personalContact: 'Personal Contacts',
    allContacts: 'All Contacts',
    fullName: 'Full Name',
    jobTitle: 'Job Title',
    phoneNumber: 'Phone Number',
    companyDepartment: 'Company / Department',
    avatarUrlOptional: 'Avatar URL (optional)',
    saveContact: 'Save Contact',
    searchContactsPlaceholder: 'Search by name, email, department...',
    importContacts: 'Import Contacts',
    exportContacts: 'Export Contacts',
    syncWithGoogleContacts: 'Sync with Google Contacts',
    // Tasklist
    syncWithGoogleTasks: 'Sync with Google Tasks',
    // Training Module
    trainingDashboard: 'Training Dashboard',
    trainingSlogan: 'Digital Classroom – Learn anytime, connect anywhere',
    myClasses: 'My Classes',
    createClass: 'Create Class',
    stream: 'Stream',
    classwork: 'Classwork',
    people: 'People',
    grades: 'Grades',
    allTopics: 'All topics',
    syncWithGoogleClassroom: 'Sync Classroom',
    // Google Sync
    connectGoogleAccount: 'Connect Google Account',
    disconnect: 'Disconnect',
    connectedAs: 'Connected as',
    syncStatus: 'Synchronization Status',
    service: 'Service',
    status: 'Status',
    sync: 'Sync',
    connected: 'Connected',
    notConnected: 'Not Connected',
    connect: 'Connect',
     // Settings Page
    profile: 'Profile',
    connectionsAndSync: 'Connections & Sync',
    effectsAndSound: 'Effects & Sound',
    aiVoiceSettings: 'AI Voice Settings',
    manageYourProfile: 'Manage your personal information.',
    customizeAppearance: 'Customize the look and feel of the application.',
    chooseLanguage: 'Choose the display language for the application.',
    manageEffects: 'Manage visual and sound effects.',
    configureAiAssistant: "Configure the AI Assistant's voice and behavior.",
    manageIntegrations: 'Manage connections and sync with external services.',
    userManagement: 'User Permissions',
    userManagementDesc: 'Manage user roles and access permissions.',
    userManagementTitle: 'Permission Management',
    userManagementSlogan: 'Build structure, protect data, empower effectively.',
    user: 'User',
    role: 'Role',
    active: 'Active',
    role_superadmin: 'Super Admin',
    role_superadmin_desc: 'Full access to all settings and user management.',
    role_admin: 'Admin',
    role_admin_desc: 'Can create and manage content, but cannot change system settings or user roles.',
    role_member: 'Member',
    role_member_desc: 'Standard access to view and interact with shared content.',
    updateRoleSuccess: 'Role updated successfully!',
    cannotChangeOwnRole: 'Cannot change your own role.',
    userList: 'User List',
    createUser: 'Create User',
    addUser: 'Add User',
    orgChart: 'Org Chart',
    orgChartConfig: 'Org Configuration',
    department: 'Department',
    position: 'Position',
    requestsAndApprovals: 'Approvals',
    requests: 'Requests',
    approvals: 'Approvals',
    newRequest: 'New Request',
    requestTitle: 'Title',
    requestType: 'Type',
    requestContent: 'Content',
    statusPending: 'Pending',
    statusApproved: 'Approved',
    statusRejected: 'Rejected',
    approve: 'Approve',
    reject: 'Reject',
    leaveRequest: 'Leave Request',
    equipmentRequest: 'Equipment Request',
    otherRequest: 'Other',
    approver: 'Approver',
    selectApprover: 'Select approver',
    recentlyViewed: 'Recently Viewed',
    websiteData: 'Administration',
    projects: 'Projects',
    websiteDataManagement: 'System Administration',
    homePage: 'Home Page',
    pages: 'Pages',
    media: 'Media Library',
    websiteSettings: 'Settings',
    // AI Widget & Settings
    visualEffects: 'Visual Effects',
    cursorTrails: 'Cursor Trails',
    cursorTrailsDesc: 'Enable cursor trail effects for smoother tracking.',
    soundEffects: 'Sound Effects',
    enableSoundEffects: 'Enable Sound Effects',
    enableSoundEffectsDesc: 'Enable sounds for clicks and interactions.',
    aiVoice: 'AI Voice',
    enableAiVoice: 'Enable Voice',
    enableAiVoiceDesc: 'Enable/disable AI text-to-speech.',
    robotEffect: 'Robot Effect',
    robotEffectDesc: 'Apply a robot voice effect to the AI.',
    voiceModel: 'Voice Model',
    voiceModelDesc: 'Choose a voice model for the AI Assistant.',
    selectVoice: 'Select Voice',
    loadingVoices: 'Loading voices...',
    // Drive & Meeting Sync
    syncWithDrive: 'Sync with Drive',
    syncWithMeetingsCalendar: 'Sync with Calendar',
    syncWithCalendar: 'Sync with Calendar',
    addToCalendar: 'Add to Google Calendar',
    syncWithGoogleChat: 'Sync with Calendar',
    // Newsfeed
    whatAreYouThinking: "What's on your mind, {{userName}}?",
    post: 'Post',
    photoVideo: 'Photo/Video',
    tagFriends: 'Tag Friends',
    feelingActivity: 'Feeling/Activity',
    checkIn: 'Check-in',
    audience: 'Audience',
    audienceCompany: 'Company Wide',
    audienceGroup: 'Your Group',
    audiencePrivate: 'Only Me',
    isFeeling: 'is feeling',
    with: 'with',
    at: 'at',
    // Check-in Module
    timekeeping: 'Timekeeping',
    timekeepingHistory: "Today's History",
    checkInSuccess: 'Checked in successfully!',
    checkOutSuccess: 'Checked out successfully!',
    currentStatus: 'Current Status',
    notCheckedIn: 'Not Checked In',
    checkedInAt: 'Checked in at',
    workingDuration: 'Working Duration',
    location: 'Location',
    date: 'Date',
    duration: 'Duration',
    checkInTime: 'Check-in',
    checkOutTime: 'Check-out',
    checkInButton: 'Check In',
    checkOutButton: 'Check Out',
    checkInBiometric: 'Biometric Check In',
    checkOutBiometric: 'Biometric Check Out',
    registerBiometric: 'Register Fingerprint',
    biometricRegistered: 'Fingerprint registered successfully!',
    biometricError: 'Fingerprint authentication error.',
    registerBiometricPrompt: 'You have not registered your fingerprint. Would you like to register now?',
    editProfile: 'Edit Profile',
    saveProfile: 'Save Profile',
    profileUpdated: 'Profile updated successfully!',
    profileUpdateError: 'Error updating profile.',
    saveSuccess: 'Settings saved successfully!',
    changeAvatar: 'Change Avatar',
    comments: 'Comments',
    addComment: 'Add comment',
    noComments: 'No comments yet.',
    writeComment: 'Write a comment...',
    weeklyWorkHours: 'Weekly Work Hours',
    hours: 'hours',
    dayMon: 'Mon',
    dayTue: 'Tue',
    dayWed: 'Wed',
    dayThu: 'Thu',
    dayFri: 'Fri',
    daySat: 'Sat',
    daySun: 'Sun',
    activeSession: 'Active Session',
    authenticating: 'Authenticating...',
    biometricsNotSupported: 'Biometrics are not supported on this device.',
    checkedIn: 'Checked In',
    checkedOut: 'Checked Out',
     // Dashboard Customization
    customizeDashboard: 'Customize',
    dashboardWidgets: 'Dashboard Widgets',
    dashboardWidgetsDesc: 'Choose which widgets to display on your dashboard.',
    upcomingEvents: 'Upcoming Events',
    quickTasks: 'Quick Tasks',
    recentNotes: 'Recent Notes',
    recentlyViewedItems: 'Recently Viewed',
    noUpcomingEvents: 'No upcoming events.',
    noPendingTasks: 'No pending tasks.',
    noRecentNotes: 'No recent notes.',
    viewAll: 'View All',
    widget_events_desc: 'Show upcoming events and meetings.',
    widget_tasks_desc: 'Show pending tasks from your lists.',
    widget_notes_desc: 'Show your most recently created notes.',
    widget_recent_desc: 'Show items you have recently accessed.',
    widget_newsfeed_desc: 'Preview the latest post on the internal newsfeed.',
    widget_checkin_desc: 'View your current check-in status.',
    widget_drive_desc: 'See recently modified files in your Drive.',
    widget_tasks_link_desc: 'Get a summary of your uncompleted tasks.',
    widget_contacts_desc: 'Quickly see a few contacts from your directory.',
    widget_calendar_link_desc: 'See upcoming events and meetings.',
    widget_notes_link_desc: 'Preview your most recent notes.',
    widget_blog_desc: 'See the latest blog post or article.',
    widget_training_desc: 'See your next upcoming class or training course.',
    widget_email_desc: 'Preview important unread emails.',
    widget_meeting_desc: 'See your next upcoming online meeting.',
    widget_chat_desc: 'See exchange channels with new messages.',
    // Global Search
    searchAllPlaceholder: 'Search articles, files, contacts...',
    noResultsFound: 'No results found.',
    resultsBlog: 'Blog Posts',
    resultsFiles: 'Files',
    resultsContacts: 'Contacts',
    resultsTasks: 'Tasks',
    resultsEvents: 'Events',
    resultsMessages: 'Messages',
    openNavigationMenu: 'Open navigation menu',
    submitSearch: 'Submit search',
    // Projects
    projectList: 'Project List',
    newProject: 'New Project',
    projectName: 'Project Name',
    projectDesc: 'Project Description',
    projectStatus: 'Status',
    projectDueDate: 'Due Date',
    projectDepartment: 'Department',
    exportCSV: 'Export CSV',
    exportPDF: 'Export PDF',
    searchProjects: 'Search projects by name or description...',
    allDepartments: 'All Departments',
    overdue: 'Overdue',
    thisWeek: 'This Week',
    thisMonth: 'This Month',
    progress: 'Progress',
  }
};

interface LanguageContextType {
  language: Language;
  setLanguage: (language: Language) => void;
  t: (key: string, replacements?: Record<string, string | number>) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [language, setLanguageState] = useState<Language>('vi');

  useEffect(() => {
    const savedLang = localStorage.getItem('language') as Language;
    if (savedLang && (savedLang === 'vi' || savedLang === 'en')) {
      setLanguageState(savedLang);
    }
  }, []);

  const setLanguage = (lang: Language) => {
    localStorage.setItem('language', lang);
    setLanguageState(lang);
  };

  const t = useCallback((key: string, replacements?: Record<string, string | number>): string => {
    let translation = translations[language][key as keyof typeof translations.vi] || key;
    if (replacements) {
        Object.keys(replacements).forEach(placeholder => {
            translation = translation.replace(`{{${placeholder}}}`, String(replacements[placeholder]));
        });
    }
    return translation;
  }, [language]);

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = (): LanguageContextType => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
